### ISSUE TITLE
Error in test: Assertion failed: number too large

### ISSUE THREAD

**Issue by christianbundy** [flumedb/aligned-block-file#4]
I'm unclear when this started happening, but I can reproduce with `npm install && npm test`.

```
Assertion failed: number too large
/home/christianbundy/src/aligned-block-file/test/read-integers.js:77
      if (!err && expectError) throw new Error('Expected error dir not occur')
                               ^

Error: Expected error dir not occur
    at /home/christianbundy/src/aligned-block-file/test/read-integers.js:77:38
    at /home/christianbundy/src/aligned-block-file/blocks.js:103:11
    at /home/christianbundy/src/aligned-block-file/blocks.js:74:11
    at get (/home/christianbundy/src/aligned-block-file/blocks.js:29:7)
    at next (/home/christianbundy/src/aligned-block-file/blocks.js:53:7)
    at /home/christianbundy/src/aligned-block-file/blocks.js:63:25
    at get (/home/christianbundy/src/aligned-block-file/blocks.js:29:7)
    at next (/home/christianbundy/src/aligned-block-file/blocks.js:53:7)
    at read (/home/christianbundy/src/aligned-block-file/blocks.js:77:7)
    at Object.readUInt64BE (/home/christianbundy/src/aligned-block-file/blocks.js:100:9)
npm ERR! Test failed.  See above for more details.
```

**Comment by dominictarr** [comment]
happens on node@10 but not node@8

**Comment by dominictarr** [comment]
it's to do with int53 module

**Comment by dominictarr** [comment]
weird, module hasn't changed in 3 years, and it only affects node@10!

**Comment by dominictarr** [comment]
oh, here is the problem: https://github.com/dannycoates/int53/blob/master/index.js#L15
console.assert throws in node 8 but only logs in 10!

**Comment by dominictarr** [comment]
but weird, there seems to be coverage for it: https://github.com/nodejs/node/blob/8b4af64f50c5e41ce0155716f294c24ccdecad03/deps/v8/test/mjsunit/console.js

**Comment by dominictarr** [comment]
will be fixed by this: https://github.com/dannycoates/int53/pull/4/files

unlikely to affect production ssb because I don't think we are using readUInt64

**Comment by christianbundy** [comment]
Resolved by https://github.com/flumedb/aligned-block-file/commit/b761f24dbcfbbdce6350dc358842de7a8d700eac
